[[minify]]
arch = "aarch64"
git-tree-sha1 = "ed7031bf639397cb58805f1ed177fc8a549e5ad0"
os = "macos"

    [[minify.download]]
    sha256 = "6cab5a15d8a7184ab24bb86739a1b72f4a3d571e61fc2ad1aa538d9cf68b9c13"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.aarch64-apple-darwin.tar.gz"
[[minify]]
arch = "aarch64"
git-tree-sha1 = "3df1e2b1d17295b37ad340e5d6c8999f8637ad8b"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "08a0814964ec4443021ae2df6c56269d7805ecc7f49453475d26c74faadbf383"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.aarch64-linux-gnu.tar.gz"
[[minify]]
arch = "aarch64"
git-tree-sha1 = "3df1e2b1d17295b37ad340e5d6c8999f8637ad8b"
libc = "musl"
os = "linux"

    [[minify.download]]
    sha256 = "08a0814964ec4443021ae2df6c56269d7805ecc7f49453475d26c74faadbf383"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.aarch64-linux-musl.tar.gz"
[[minify]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a277ce68c836f3755dec151a1e0872fcf95fabfa"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "85d46932a7d83d6c9195c9975c4b9bd003d3c960078f2c8ccc936610b6c0a97f"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.armv6l-linux-gnueabihf.tar.gz"
[[minify]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a277ce68c836f3755dec151a1e0872fcf95fabfa"
libc = "musl"
os = "linux"

    [[minify.download]]
    sha256 = "85d46932a7d83d6c9195c9975c4b9bd003d3c960078f2c8ccc936610b6c0a97f"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.armv6l-linux-musleabihf.tar.gz"
[[minify]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3284e8785740240a7296cdfd772b2607c50247a"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "c7466d7da6984c74cef5f7478c0d45df3fda8efb3833923130c340474b437616"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.armv7l-linux-gnueabihf.tar.gz"
[[minify]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3284e8785740240a7296cdfd772b2607c50247a"
libc = "musl"
os = "linux"

    [[minify.download]]
    sha256 = "c7466d7da6984c74cef5f7478c0d45df3fda8efb3833923130c340474b437616"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.armv7l-linux-musleabihf.tar.gz"
[[minify]]
arch = "i686"
git-tree-sha1 = "fa2b49d49593b669c80d156e525beb052ae3efc9"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "8fb5c3e79514640c4d7530c636c56ea55f03c67d81e7afd693986428b96dd3c2"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.i686-linux-gnu.tar.gz"
[[minify]]
arch = "i686"
git-tree-sha1 = "fa2b49d49593b669c80d156e525beb052ae3efc9"
libc = "musl"
os = "linux"

    [[minify.download]]
    sha256 = "8fb5c3e79514640c4d7530c636c56ea55f03c67d81e7afd693986428b96dd3c2"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.i686-linux-musl.tar.gz"
[[minify]]
arch = "i686"
git-tree-sha1 = "e177b4746dff6b955b8cd630a9068a081002d8ba"
os = "windows"

    [[minify.download]]
    sha256 = "cd077c4dbe512207771929c8e1df5a93312eb5702632b0daa99df2cefad146a0"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.i686-w64-mingw32.tar.gz"
[[minify]]
arch = "powerpc64le"
git-tree-sha1 = "6615c7ceeff5e332e31c1845aba472c08935c5fa"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "e6e74e3a36616d2a46e7aa65f8b42ec21544379897c6c49e72a32f8519f5ec6d"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.powerpc64le-linux-gnu.tar.gz"
[[minify]]
arch = "x86_64"
git-tree-sha1 = "5c7de3db272732dec1cca65ad10face1e3a52ea0"
os = "macos"

    [[minify.download]]
    sha256 = "293b28c9d73ea4338bf0a13e747663524f7fe4572c8f36f4eed6953354e24ab1"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.x86_64-apple-darwin.tar.gz"
[[minify]]
arch = "x86_64"
git-tree-sha1 = "0434ae6839e1cf7b86871c8aa99db39b032c8fc4"
libc = "glibc"
os = "linux"

    [[minify.download]]
    sha256 = "0bede2642b4b5534ab41479897c2b71ed1e277dc6e1f8ddb4f187761ccece88d"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.x86_64-linux-gnu.tar.gz"
[[minify]]
arch = "x86_64"
git-tree-sha1 = "7305e953ca6fb2f02c580a39558d1eb6c068a6f8"
libc = "musl"
os = "linux"

    [[minify.download]]
    sha256 = "a6d6a50f68a8c6cbbd35050a6bb99af5a0cb95f195ecfc776ba549f203342173"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.x86_64-linux-musl.tar.gz"
[[minify]]
arch = "x86_64"
git-tree-sha1 = "d581be4c1af8fb06f10c075e3cda64639cafb68d"
os = "freebsd"

    [[minify.download]]
    sha256 = "7474db0312193c705e62b2c8357483580bed3dd1c59752d4a54272f26eee89c5"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.x86_64-unknown-freebsd.tar.gz"
[[minify]]
arch = "x86_64"
git-tree-sha1 = "1dbc6c0a847e337a29934fd54c6cbd6ec912d3cc"
os = "windows"

    [[minify.download]]
    sha256 = "eea00410b1347d26d3eb58d3fbe28a095eda686e848e3cdfe7b622340578b4e9"
    url = "https://github.com/JuliaBinaryWrappers/minify_jll.jl/releases/download/minify-v2.20.20+0/minify.v2.20.20.x86_64-w64-mingw32.tar.gz"
